tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-secondary": "#033258",
                "on-tertiary": "#213611",
                "error": "#ffb4ab",
                "surface-tint": "#97cfe0",
                "surface-container-high": "#242a36",
                "inverse-surface": "#dde2f2",
                "on-background": "#dde2f2",
                "secondary": "#a6c9f8",
                "on-primary-container": "#0c4f5d",
                "on-error": "#690005",
                "on-secondary-container": "#98bbe9",
                "tertiary-fixed": "#cfebb6",
                "on-secondary-fixed-variant": "#234970",
                "surface-bright": "#333945",
                "primary-container": "#88c0d0",
                "tertiary": "#c0dca8",
                "secondary-fixed-dim": "#a6c9f8",
                "surface-variant": "#2f3541",
                "inverse-on-surface": "#2b313c",
                "on-tertiary-fixed-variant": "#364d26",
                "primary": "#a3dcec",
                "surface-container-low": "#161c27",
                "tertiary-fixed-dim": "#b4cf9c",
                "on-surface": "#dde2f2",
                "on-primary-fixed": "#001f26",
                "outline": "#8a9295",
                "surface-container-lowest": "#080e19",
                "inverse-primary": "#2b6674",
                "on-tertiary-fixed": "#0c2001",
                "on-error-container": "#ffdad6",
                "secondary-fixed": "#d2e4ff",
                "on-secondary-fixed": "#001c37",
                "tertiary-container": "#a5c08e",
                "on-surface-variant": "#c0c8cb",
                "primary-fixed-dim": "#97cfe0",
                "secondary-container": "#264b73",
                "outline-variant": "#40484b",
                "surface-container-highest": "#2f3541",
                "on-tertiary-container": "#384f27",
                "primary-fixed": "#b3ecfc",
                "surface-container": "#1a202b",
                "on-primary": "#003640",
                "surface-dim": "#0d131e",
                "error-container": "#93000a",
                "background": "#0d131e",
                "on-primary-fixed-variant": "#094e5c",
                "surface": "#0d131e"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "sm": "8px",
                "xl": "48px",
                "gutter": "24px",
                "md": "16px",
                "xxl": "96px",
                "container-max": "1000px",
                "unit": "4px",
                "lg": "24px",
                "xs": "4px"
            },
            "fontFamily": {
                "display": ["Inter"],
                "label-sm": ["Inter"],
                "card-title": ["Inter"],
                "body-main": ["Inter"],
                "header-cat": ["Inter"]
            },
            "fontSize": {
                "display": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
                "label-sm": ["13px", {"lineHeight": "1", "letterSpacing": "0", "fontWeight": "500"}],
                "card-title": ["16px", {"lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "500"}],
                "body-main": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
                "header-cat": ["12px", {"lineHeight": "1.5", "letterSpacing": "0.1em", "fontWeight": "700"}]
            }
        },
    },
};
